server:
  port: 8081 #指定server绑定的地址
  tomcat:
      uri-encoding: UTF-8 #默认字符集
  compression:
      enabled: true #是否开启压缩，默认为false.
spring:
  profiles:
    active: test  #制定配置文件
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #指定时间格式及时差
    time-zone: GMT+8



